#!/usr/bin/env python3.11
"""Compose ONLY the requested room: walls, floor, window, one table + one chair.
Car and NPC are sprites the ROM draws; here we just reserve their footprints as
solid. Outputs res/room.png, assets/room_preview.png, src/roomcol.h."""
from PIL import Image

SHEET = "assets/rpg/Spritesheet/roguelikeSheet_transparent.png"
PITCH, TILE, W, H = 17, 16, 20, 14
sheet = Image.open(SHEET).convert("RGBA")

def tile(c, r, fh=False, fv=False):
    t = sheet.crop((c * PITCH, r * PITCH, c * PITCH + TILE, r * PITCH + TILE))
    if fh: t = t.transpose(Image.FLIP_LEFT_RIGHT)
    if fv: t = t.transpose(Image.FLIP_TOP_BOTTOM)
    return t

room = Image.new("RGBA", (W * 16, H * 16), (0, 0, 0, 255))
solid = [[0] * W for _ in range(H)]

FLOOR, WALL = (8, 26), (3, 26)
for y in range(H):
    for x in range(W):
        edge = x in (0, W - 1) or y in (0, H - 1)
        room.alpha_composite(tile(*(WALL if edge else FLOOR)), (x * 16, y * 16))
        if edge: solid[y][x] = 1

def place(c, r, x, y, fh=False, fv=False, block=True):
    room.alpha_composite(tile(c, r, fh, fv), (x * 16, y * 16))
    if block: solid[y][x] = 1

# window in the back wall (sky window)
place(41, 4, 10, 0, block=False)

# one table + one chair (chair to the left, facing right toward the table)
TABLE_X, TABLE_Y = 7, 6
place(16, 0, TABLE_X, TABLE_Y)                 # table
place(19, 4, TABLE_X - 1, TABLE_Y, fh=True)    # chair facing the table

# reserve car + NPC footprints (drawn as sprites by the ROM)
CAR_TX, CAR_TY = 9, 8      # 32x32 full car sprite -> 2x2 tiles
NPC_TX, NPC_TY = 13, 7     # 16x16 -> 1 tile
for dy in range(2):
    for dx in range(2):
        solid[CAR_TY + dy][CAR_TX + dx] = 1
solid[NPC_TY][NPC_TX] = 1

room.convert("RGB").save("assets/room_preview.png")
q = room.convert("RGB").quantize(colors=16, method=Image.MEDIANCUT)
q.save("res/room.png")

with open("src/roomcol.h", "w") as f:
    f.write("// generated by tools/compose_room.py -- 1 = solid\n")
    f.write(f"#define ROOM_W {W}\n#define ROOM_H {H}\n")
    f.write(f"#define CAR_TX {CAR_TX}\n#define CAR_TY {CAR_TY}\n")
    f.write(f"#define NPC_TX {NPC_TX}\n#define NPC_TY {NPC_TY}\n")
    f.write("static const u8 solid[ROOM_H][ROOM_W] = {\n")
    for row in solid:
        f.write("    {" + ",".join(map(str, row)) + "},\n")
    f.write("};\n")

print("done; palette", len(q.getcolors()))
