#!/usr/bin/env python3
"""Build res/*.png from the Sonic 2 disassembly, using only the standard library.

Assets are generated by a script rather than committed as finished art, so any
sprite can be swapped for an original one later without touching the game code.

  python3 tools/make_assets.py

The Tornado is Nemesis-compressed art plus a sprite mapping in s2disasm: the art
is a bag of 8x8 tiles, and the mapping says where each rectangle of tiles sits
relative to the object's origin. We decompress, assemble the four propeller
frames side by side, and write an indexed PNG - which is what SGDK's rescomp
wants, and it keeps the palette under our control instead of letting a converter
pick one.
"""

import math
import os
import re
import struct
import zlib

import nemesis

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
RES = os.path.join(PROJ, "res")
ASSETS = os.path.join(PROJ, "assets")
S2 = os.path.normpath(os.path.join(PROJ, "..", "..", "mods", "sonic2", "s2disasm"))

ART = os.path.join(S2, "art", "nemesis", "The Tornado.nem")
MAPS = os.path.join(S2, "mappings", "sprite", "objB2_a.asm")
# Every Tornado mapping piece asks for palette line 0, which in Sonic 2 is the
# shared character palette - not the level's. Under the Sky Chase lines the
# plane comes out yellow and the pilot's colours are wrong; under this one it is
# the red Tornado it actually is, and Tails looks like Tails. It also means the
# plane and Sonic share one palette line.
PAL = os.path.join(S2, "art", "palettes", "SonicAndTails.bin")

# Propeller cycle for the Sonic-piloted Tornado (Ani_objB2_a, script 0).
FRAMES = [0, 1, 2, 3]

# The cockpit piece is written as tile $2A0 in the mappings, which is outside
# this art file. In Sonic 2 that is deliberate: the pilot is drawn from whichever
# character you are playing, so the mapping points at the player's own VRAM.
# We have no player, and the Tornado's art carries an unused 3x2 pilot at
# $18-$1D (the one gap in the file), so we point the piece there instead.
PILOT_FIXUP = {0x2A0: 0x18}

# Measured Mega Drive output for each 3-bit colour component.
MD_LEVELS = (0, 52, 87, 116, 144, 172, 206, 255)


def write_indexed_png(path, width, height, palette, rows):
    """Indexed-colour PNG. rows is a list of bytearrays of palette indices."""
    def chunk(tag, data):
        c = tag + data
        return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 3, 0, 0, 0)  # 8-bit, indexed
    plte = b"".join(bytes(c) for c in palette)
    # Colour 0 is the Mega Drive's transparent entry; mark it transparent here
    # too so the sprite previews correctly in an image viewer.
    trns = b"\x00" + b"\xff" * (len(palette) - 1)

    raw = b"".join(b"\x00" + bytes(r) for r in rows)  # filter 0 per scanline
    png = (b"\x89PNG\r\n\x1a\n"
           + chunk(b"IHDR", ihdr)
           + chunk(b"PLTE", plte)
           + chunk(b"tRNS", trns)
           + chunk(b"IDAT", zlib.compress(raw, 9))
           + chunk(b"IEND", b""))
    with open(path, "wb") as f:
        f.write(png)
    return len(png)


def read_md_palette(path, line=0):
    """One 16-colour line out of a Mega Drive palette blob (0000BBB0GGG0RRR0)."""
    d = open(path, "rb").read()
    out = []
    for i in range(16):
        w = struct.unpack_from(">H", d, (line * 16 + i) * 2)[0]
        r = MD_LEVELS[(w >> 1) & 7]
        g = MD_LEVELS[(w >> 5) & 7]
        b = MD_LEVELS[(w >> 9) & 7]
        out.append((r, g, b))
    return out


def _num(tok):
    tok = tok.strip()
    neg = tok.startswith("-")
    if neg:
        tok = tok[1:]
    v = int(tok[1:], 16) if tok.startswith("$") else int(tok, 10)
    return -v if neg else v


def read_frame_table(path, header_kw, item_kw, parse_item):
    """Frames from an AS mapping/DPLC file, ordered by its offsets table.

    File order is NOT frame order. Identical frames are deduplicated by stacking
    several labels on one body (.frame88 sits directly above .frame87), so a
    frame can be missing from the file entirely and still exist in the table.
    Reading positionally silently shifts every later frame - which shows up as
    sprites assembled out of another frame's tiles. So: resolve labels.
    """
    order = []
    bodies = {}
    pending = []
    cur = None

    label_re = re.compile(r"^([A-Za-z_.][\w.]*):")

    for raw in open(path):
        line = raw.strip()
        if not line:
            continue
        if "mappingsTableEntry" in line:
            order.append(line.split()[-1])
            continue

        m = label_re.match(line)
        if m:
            name = m.group(1)
            rest = line[m.end():].strip()
            if header_kw in rest:
                cur = []
                for p in pending + [name]:
                    bodies[p] = cur
                pending = []
            elif not rest:
                pending.append(name)        # a bare label aliasing what follows
            continue

        if line.startswith(item_kw):
            cur.append(parse_item(line))

    return [bodies[name] for name in order]


def read_dplc(path):
    """Every frame of a SonicDplcVer=2 DPLC list, as [(tile_count, art_tile)].

    Player characters have far more animation than fits in their VRAM window, so
    each frame carries a list of "copy N tiles from art offset X" cues, executed
    into a small scratch area. The sprite mapping then indexes that scratch area,
    not the art file - so a frame has to be rebuilt before it can be drawn.
    """
    def entry(line):
        args = [_num(a) for a in line.split(None, 1)[1].split(",")]
        return (args[0], args[1])

    return read_frame_table(path, "dplcHeader", "dplcEntry", entry)


def dplc_tiles(art, cues):
    """The scratch tile buffer a DPLC frame builds, as raw tile bytes."""
    out = bytearray()
    for count, offset in cues:
        start = offset * 32
        out += art[start:start + count * 32]
    return bytes(out)


def read_mappings(path):
    """Every frame in a SonicMappingsVer=2 sprite mapping file, as piece lists.

    A piece is (x, y, tiles_wide, tiles_tall, first_tile, xflip, yflip).
    """
    def piece(line):
        a = [_num(v) for v in line.split(None, 1)[1].split(",")]
        return (a[0], a[1], a[2], a[3], PILOT_FIXUP.get(a[4], a[4]), a[5], a[6])

    return read_frame_table(path, "spriteHeader", "spritePiece", piece)


def draw_piece(canvas, ox, oy, tiles, tile_count, piece):
    x, y, w, h, first, xf, yf = piece
    # Tiles are stored column-major within a piece: down first, then across.
    for cx in range(w):
        for cy in range(h):
            t = first + cx * h + cy
            if t >= tile_count:
                continue                        # piece points outside this art
            px = tile_to_pixels(tiles, t)
            for ty in range(8):
                sy = (7 - ty) if yf else ty
                for tx in range(8):
                    sx = (7 - tx) if xf else tx
                    v = px[sy][sx]
                    if v == 0:
                        continue                # transparent
                    dx = ox + x + cx * 8 + tx
                    dy = oy + y + cy * 8 + ty
                    if 0 <= dy < len(canvas) and 0 <= dx < len(canvas[0]):
                        canvas[dy][dx] = v


def tile_to_pixels(tiles, index):
    return nemesis.tile_to_pixels(tiles, index)


def frame_bounds(pieces):
    xs, ys, xe, ye = 9999, 9999, -9999, -9999
    for x, y, w, h, _t, _xf, _yf in pieces:
        xs = min(xs, x); ys = min(ys, y)
        xe = max(xe, x + w * 8); ye = max(ye, y + h * 8)
    return xs, ys, xe, ye


def build_tornado():
    art, tile_count = nemesis.decompress(open(ART, "rb").read())
    frames = read_mappings(MAPS)
    palette = read_md_palette(PAL, 0)

    used = [frames[i] for i in FRAMES]

    # One box big enough for every frame, so the sprite does not jitter as the
    # propeller animates, rounded up to whole tiles for rescomp.
    xs = min(frame_bounds(f)[0] for f in used)
    ys = min(frame_bounds(f)[1] for f in used)
    xe = max(frame_bounds(f)[2] for f in used)
    ye = max(frame_bounds(f)[3] for f in used)
    fw = ((xe - xs) + 7) // 8 * 8
    fh = ((ye - ys) + 7) // 8 * 8

    sheet_w = fw * len(used)
    rows = [bytearray(sheet_w) for _ in range(fh)]
    for i, pieces in enumerate(used):
        for p in pieces:
            draw_piece(rows, i * fw - xs, -ys, art, tile_count, p)

    out = os.path.join(RES, "tornado.png")
    n = write_indexed_png(out, sheet_w, fh, palette, rows)
    print("tornado.png  %d frames of %dx%d (%d x %d tiles)  %d bytes"
          % (len(used), fw, fh, fw // 8, fh // 8, n))
    return fw // 8, fh // 8


def build_sonic():
    """Sonic, standing, for the upper wing.

    In Sky Chase the Tornado is an ordinary solid object and Sonic simply stands
    on it, so the standing frame is the authentic pose - there is no special
    riding animation to find. (SonAni_Float is for being carried by Tails, and
    renders as a symmetric mid-air curl that reads as nonsense on a wing.)

    His art is uncompressed but DPLC-streamed, so each frame has to be rebuilt
    from its cue list before the mapping can be drawn against it. He also has his
    own palette line - the shared character palette, not the level's.
    """
    art = open(os.path.join(S2, "art", "uncompressed", "Sonic's art.bin"), "rb").read()
    maps = read_mappings(os.path.join(S2, "mappings", "sprite", "Sonic.asm"))
    dplc = read_dplc(os.path.join(S2, "mappings", "spriteDPLC", "Sonic.asm"))
    palette = read_md_palette(PAL, 0)

    frame = 1                                   # standing
    pieces = maps[frame]
    xs, ys, xe, ye = frame_bounds(pieces)
    w = ((xe - xs) + 7) // 8 * 8
    h = ((ye - ys) + 7) // 8 * 8

    rows = [bytearray(w) for _ in range(h)]
    buf = dplc_tiles(art, dplc[frame])
    for p in pieces:
        draw_piece(rows, -xs, -ys, buf, len(buf) // 32, p)

    out = os.path.join(RES, "sonic.png")
    n = write_indexed_png(out, w, h, palette, rows)
    print("sonic.png    %dx%d (%d x %d tiles)  %d bytes" % (w, h, w // 8, h // 8, n))
    return w // 8, h // 8


def build_music():
    """Copy the track into res/ with a loop point set.

    only_air.vgm ships with its loop offset field at zero - no loop point at all
    - so it plays once and stops however the driver is configured. Nothing in
    SGDK can loop a track that does not say where to loop to. Pointing the loop
    at the start of the VGM data makes it repeat the whole piece.
    """
    src = os.path.join(ASSETS, "only_air.vgm")
    d = bytearray(open(src, "rb").read())

    data_abs = 0x34 + struct.unpack_from("<I", d, 0x34)[0]
    total = struct.unpack_from("<I", d, 0x18)[0]
    struct.pack_into("<I", d, 0x1C, data_abs - 0x1C)    # loop offset, relative
    struct.pack_into("<I", d, 0x20, total)              # samples in the loop

    out = os.path.join(RES, "only_air.vgm")
    with open(out, "wb") as f:
        f.write(d)
    print("only_air.vgm loop set: whole track, %d samples (%.0fs)"
          % (total, total / 44100.0))


def build_airliner():
    """A generic airliner for passing traffic - drawn here, not sourced.

    Deliberately plain and to scale: at cruise another jet is a small pale shape
    a long way off, so it is one sprite with no variations, no landing gear, and
    no collision. Original artwork; the reference that prompted it was only used
    as a description of what an airliner looks like from the side.

    Colours are Mega Drive 3-bit triples for the same reason as the sky.
    """
    # 128 wide is the largest a single Mega Drive sprite can be (16x16 tiles),
    # and that is deliberate: an airliner has to read as bigger than the 120px
    # Tornado, because it is.
    W, H = 128, 48
    CX_NOSE, CX_TAIL = 116, 8
    CY = 22                                     # fuselage centre line

    # 0 clear, 1 white, 2 shade, 3 grey, 4 navy, 5 blue, 6 glass
    palette = [(0, 0, 0),
               (MD_LEVELS[7], MD_LEVELS[7], MD_LEVELS[7]),
               (MD_LEVELS[6], MD_LEVELS[6], MD_LEVELS[7]),
               (MD_LEVELS[4], MD_LEVELS[4], MD_LEVELS[5]),
               (MD_LEVELS[0], MD_LEVELS[1], MD_LEVELS[3]),
               (MD_LEVELS[0], MD_LEVELS[2], MD_LEVELS[5]),
               (MD_LEVELS[1], MD_LEVELS[1], MD_LEVELS[2])]
    palette += [(0, 0, 0)] * (16 - len(palette))
    CLEAR, WHITE, SHADE, GREY, NAVY, BLUE, GLASS = range(7)

    px = [bytearray(W) for _ in range(H)]

    def put(x, y, c):
        if 0 <= x < W and 0 <= y < H:
            px[y][x] = c

    def tri(pts, c):
        """Fill a triangle, scanline by scanline."""
        ys = [p[1] for p in pts]
        for y in range(min(ys), max(ys) + 1):
            xs = []
            for i in range(3):
                (x0, y0), (x1, y1) = pts[i], pts[(i + 1) % 3]
                if y0 == y1:
                    continue
                if min(y0, y1) <= y <= max(y0, y1):
                    xs.append(x0 + (x1 - x0) * (y - y0) // (y1 - y0))
            if xs:
                for x in range(min(xs), max(xs) + 1):
                    put(x, y, c)

    def ellipse(cx, cy, rx, ry, c):
        for y in range(cy - ry, cy + ry + 1):
            dy = (y - cy) * 256 // ry
            span = rx * _isqrt(max(0, 65536 - dy * dy)) // 256
            for x in range(cx - span, cx + span + 1):
                put(x, y, c)

    # The near wing only, rooted mid-fuselage under the cabin windows rather
    # than hung off the belly, sweeping back and finishing just below the hull.
    # Kept small deliberately: a wing big enough to dominate the silhouette
    # invites the eye to look for the far wing, which a side view does not show.
    tri([(88, 26), (58, 26), (36, 38)], SHADE)
    tri([(88, 26), (36, 38), (54, 38)], SHADE)
    tri([(88, 26), (74, 26), (50, 34)], GREY)   # lit leading edge

    # Engine: a rounded nacelle tucked under the wing root. The first version
    # was a literal rectangle, which is the square block that showed up here.
    ellipse(60, 34, 12, 4, GREY)
    ellipse(60, 34, 10, 3, BLUE)

    # Tailplane: a small surface at the top of the tail cone. It used to be a
    # wedge running out to x=0 BELOW the hull, which read as debris trailing off
    # the back rather than as part of the aircraft.
    tri([(6, 19), (26, 19), (26, 15)], SHADE)

    # Fin: swept, not a symmetric triangle. The leading edge rakes back from the
    # root and the trailing edge is near vertical, finishing in a short tip
    # chord rather than a point.
    tri([(12, 14), (42, 14), (28, 2)], NAVY)
    tri([(12, 14), (28, 2), (22, 2)], NAVY)
    tri([(19, 13), (37, 13), (28, 5)], BLUE)

    # Fuselage: a tube that tapers to a cone at the tail and a round nose.
    for x in range(CX_TAIL, CX_NOSE + 1):
        half = 8
        if x > 100:
            half = 8 - (x - 100) * 6 // (CX_NOSE - 100)     # nose
        elif x < 26:
            half = 2 + (x - CX_TAIL) * 6 // (26 - CX_TAIL)  # tail cone
        for y in range(CY - half, CY + half + 1):
            c = WHITE
            if y >= CY + half - 1:
                c = NAVY                        # belly
            elif y == CY + half - 2:
                c = BLUE                        # cheatline
            elif y == CY - half:
                c = SHADE                       # lit top edge
            put(x, y, c)

    # Cabin windows, and the flight deck up front.
    for x in range(34, 101, 6):
        for dx in range(2):
            put(x + dx, CY - 3, GLASS)
            put(x + dx, CY - 2, GLASS)
    for x in range(104, 112):
        put(x, CY - 4, GLASS)
        put(x, CY - 3, GLASS)

    out = os.path.join(RES, "airliner.png")
    n = write_indexed_png(out, W, H, palette, px)
    print("airliner.png %dx%d (%d x %d tiles)  %d bytes" % (W, H, W // 8, H // 8, n))
    return W // 8, H // 8


class _Rand(object):
    """A tiny deterministic PRNG, so a given seed always builds the same sky."""

    def __init__(self, seed):
        self.s = seed & 0xFFFFFFFF

    def next(self, n):
        self.s = (self.s * 1103515245 + 12345) & 0x7FFFFFFF
        return (self.s >> 8) % n if n else 0


def _isqrt(v):
    r = 0
    while (r + 1) * (r + 1) <= v:
        r += 1
    return r


def build_sky():
    """PLACEHOLDER sky, generated rather than drawn - a vertical gradient with a
    few cloud bands, purely to prove scrolling. Replace with real art later; the
    game only cares that it is a tile-aligned indexed image.

    512x256 is deliberate: that is exactly one Mega Drive scroll plane at the
    default 64x32 tile size, so horizontal scrolling wraps seamlessly instead of
    running off the end of a screen-sized image."""
    w, h = 512, 256

    # The sky owns a whole palette line, so spend it: eleven blues instead of
    # six roughly halves the size of each step, which is most of the fix for
    # visible banding. Three cloud tones give clouds a lit top and a shaded
    # underside rather than a flat white blob.
    BLUES = 11
    CLOUD_HI, CLOUD_MID, CLOUD_LO = BLUES + 1, BLUES + 2, BLUES + 3

    # Written as Mega Drive 3-bit triples, not as pretty 24-bit values that get
    # squashed down later. The hardware has eight levels per channel, so an
    # interpolated RGB ramp lands wherever rounding puts it - and a blue whose
    # green catches up with its blue reads as teal. Every step here keeps
    # blue > green > red by construction, and MD_LEVELS round-trips exactly.
    RAMP = ((0, 1, 4), (0, 2, 5), (1, 2, 5), (1, 3, 6), (2, 3, 6), (2, 4, 6),
            (3, 4, 7), (3, 5, 7), (4, 5, 7), (4, 6, 7), (5, 6, 7))
    assert len(RAMP) == BLUES

    palette = [(0, 0, 0)]
    palette += [(MD_LEVELS[r], MD_LEVELS[g], MD_LEVELS[b]) for r, g, b in RAMP]
    palette += [(0xFF, 0xFF, 0xFF), (0xE6, 0xF0, 0xFB), (0xC2, 0xD8, 0xEE)]
    palette += [(0, 0, 0)] * (16 - len(palette))

    # A 16-colour gradient over 256 rows means hard steps, which is exactly what
    # the first pass looked like. Dithering the boundary with a Bayer matrix
    # trades them for a checkered blend - the standard trick for this era, and it
    # costs nothing at runtime since it is baked into the tiles.
    bayer = ((0, 8, 2, 10), (12, 4, 14, 6), (3, 11, 1, 9), (15, 7, 13, 5))
    SEAM = 5                    # sixteenths of a band that get dithered

    rows = []
    for y in range(h):
        # The sky now scrolls vertically and wraps, so a straight top-to-bottom
        # gradient would show a hard seam every 256 pixels of climb. This one is
        # periodic - row 0 and row h-1 are the same shade - which tiles cleanly
        # and reads as broad haze layers. Absolute "deeper when higher" is not
        # baked in here at all; the runtime tints the palette by altitude, which
        # is both seamless and actually tied to how high you are.
        t = (1.0 - math.cos(2.0 * math.pi * y / h)) / 2.0
        pos = int(t * (BLUES - 1) * 16)
        band = 1 + pos // 16
        frac = pos % 16                  # how far into the NEXT band we are
        # Dither only the seam between bands. Blending across the full band
        # stipples the entire sky, which just reads as dirt; a narrow blended
        # boundary with clean flat colour either side reads as sky.
        row = bytearray(w)
        if frac < 16 - SEAM:
            for x in range(w):
                row[x] = band
        else:
            t = (frac - (16 - SEAM)) * 16 // SEAM
            for x in range(w):
                row[x] = band + 1 if t > bayer[y & 3][x & 3] else band
        rows.append(row)

    # Clouds. The first pass drew every cloud as the same flat lozenge, which is
    # why they read as identical stamps. These are unions of overlapping ellipse
    # lobes at varied sizes, so no two come out the same shape, and they are
    # shaded top-lit. Deterministic: same seed, same sky, every build.
    rnd = _Rand(0x7A11)

    def blob(cx, cy, rx, ry, mask):
        for y in range(cy - ry, cy + ry + 1):
            dy = (y - cy) * 256 // ry
            span = rx * _isqrt(max(0, 65536 - dy * dy)) // 256
            for x in range(cx - span, cx + span + 1):
                mask[y % h][x % w] = 1

    # Sparse, and gathered into a deck rather than scattered evenly. Because the
    # sky wraps vertically, clouds cannot be pinned to one true altitude - the
    # image repeats - but confining them to one part of the cycle gives decks
    # with clear air between, so climbing takes you out of cloud and back in.
    for _ in range(7):
        cx = rnd.next(w)
        cy = 72 + rnd.next(112)
        scale = 4 + rnd.next(9)                 # small wisp .. big bank
        mask = [bytearray(w) for _ in range(h)]
        for i in range(2 + rnd.next(4)):
            blob(cx + rnd.next(scale * 5) - scale * 2,
                 cy + rnd.next(scale) - scale // 2,
                 max(3, scale + rnd.next(scale * 2)),
                 max(2, scale // 2 + rnd.next(scale // 2 + 1)),
                 mask)
            del i

        # Shade by depth from the cloud's own top edge, so the lit surface
        # follows the lumpy silhouette instead of a straight line.
        for x in range(w):
            top = None
            for y in range(h):
                if not mask[y][x]:
                    top = None
                    continue
                if top is None:
                    top = y
                d = y - top
                rows[y][x] = CLOUD_HI if d < 3 else (CLOUD_MID if d < 7 else CLOUD_LO)

    out = os.path.join(RES, "sky.png")
    n = write_indexed_png(out, w, h, palette, rows)
    print("sky.png      %dx%d  %d bytes  (PLACEHOLDER)" % (w, h, n))


if __name__ == "__main__":
    os.makedirs(RES, exist_ok=True)
    tw, th = build_tornado()
    sw, sh = build_sonic()
    aw, ah = build_airliner()
    build_sky()
    build_music()
    print()
    print("res/tornado.res SPRITE dimensions: plane %d %d, sonic %d %d, "
          "airliner %d %d" % (tw, th, sw, sh, aw, ah))
